import type { FlowKanbanState } from './types'
import { addDaysIso } from '@/shared/lib/date'

export const initialFlowState: FlowKanbanState = {
  project: {
    id: 'project_001',
    name: 'Flow Kanban MVP',
    description: '工程フローから必要なタスクだけを自動生成するカンバン。',
    status: 'draft',
  },
  processes: [
    {
      id: 'process_requirements',
      name: '要件定義',
      description: '目的、ユーザー、MVP範囲を固める。',
      position: { x: 80, y: 120 },
      completedAt: null,
    },
    {
      id: 'process_design',
      name: '設計',
      description: 'DB、API、画面、状態遷移を設計する。',
      position: { x: 380, y: 120 },
      completedAt: null,
    },
    {
      id: 'process_frontend',
      name: 'フロントエンド実装',
      description: '工程フロー、カンバン、フォームを作る。',
      position: { x: 690, y: 30 },
      completedAt: null,
    },
    {
      id: 'process_backend',
      name: 'バックエンド実装',
      description: 'REST API、WebSocket、永続化を作る。',
      position: { x: 690, y: 230 },
      completedAt: null,
    },
    {
      id: 'process_test',
      name: '結合テスト',
      description: '分岐と合流を含む自動生成を検証する。',
      position: { x: 1020, y: 120 },
      completedAt: null,
    },
  ],
  edges: [
    {
      id: 'edge_requirements_design',
      fromProcessId: 'process_requirements',
      toProcessId: 'process_design',
    },
    {
      id: 'edge_design_frontend',
      fromProcessId: 'process_design',
      toProcessId: 'process_frontend',
    },
    {
      id: 'edge_design_backend',
      fromProcessId: 'process_design',
      toProcessId: 'process_backend',
    },
    {
      id: 'edge_frontend_test',
      fromProcessId: 'process_frontend',
      toProcessId: 'process_test',
    },
    {
      id: 'edge_backend_test',
      fromProcessId: 'process_backend',
      toProcessId: 'process_test',
    },
  ],
  taskTemplates: [
    {
      id: 'template_req_1',
      processId: 'process_requirements',
      title: 'MVP範囲を確定する',
      description: '対象機能と対象外をREADMEに固定する。',
      dueDate: addDaysIso(0),
      orderIndex: 1,
    },
    {
      id: 'template_req_2',
      processId: 'process_requirements',
      title: 'ユーザーフローを確認する',
      description: 'プロジェクト開始から完了までの操作を確認する。',
      dueDate: addDaysIso(1),
      orderIndex: 2,
    },
    {
      id: 'template_design_1',
      processId: 'process_design',
      title: 'DB制約を設計する',
      description: '重複生成防止と自己接続禁止を設計する。',
      dueDate: addDaysIso(2),
      orderIndex: 1,
    },
    {
      id: 'template_design_2',
      processId: 'process_design',
      title: 'ドメイン関数を分割する',
      description: '開始判定、完了判定、タスク生成を分ける。',
      dueDate: addDaysIso(3),
      orderIndex: 2,
    },
    {
      id: 'template_fe_1',
      processId: 'process_frontend',
      title: '工程フロー画面を作る',
      description: 'ノードとエッジを見える形にする。',
      dueDate: addDaysIso(4),
      orderIndex: 1,
    },
    {
      id: 'template_fe_2',
      processId: 'process_frontend',
      title: 'カンバン操作を作る',
      description: '列移動で状態を更新する。',
      dueDate: addDaysIso(5),
      orderIndex: 2,
    },
    {
      id: 'template_be_1',
      processId: 'process_backend',
      title: 'REST APIを作る',
      description: 'プロジェクト、工程、タスクのAPIを用意する。',
      dueDate: addDaysIso(4),
      orderIndex: 1,
    },
    {
      id: 'template_be_2',
      processId: 'process_backend',
      title: 'WebSocket通知を作る',
      description: '変更イベントをプロジェクト単位で配信する。',
      dueDate: addDaysIso(6),
      orderIndex: 2,
    },
    {
      id: 'template_test_1',
      processId: 'process_test',
      title: '合流工程を検証する',
      description: 'FEとBEの両工程が終わるまで生成されないことを確認する。',
      dueDate: addDaysIso(7),
      orderIndex: 1,
    },
  ],
  tasks: [],
  events: [],
}
